# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a02c55c3b2738a3ee493adf3daf10d4820a55447a6929df54ddab57b24a388b6103fdf2be3c9f4de384c2b3f390b5c49cc158a0637e19acdef52dd69f794e7a

test:
  secret_key_base: 756e4bd5220eef7ad0869521dda69656dc6052aef13487bbc931787669b5de12caa6cbb7fd680e759a5512fab6e7cd2ed9ad3430aa532fa5401d7621c6f1690a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
